### ISSUE TITLE
(Question) What ROMs to use this kernel? (Lastest Tulip kernel)

### ISSUE THREAD

**Issue by enessmr** [user-why-red/san_kernel_releases#1]
What Android 10 ROMs should i use for this? What ROMs are compatible?

**Comment by user-why-red** [comment]
You can use it(CrystalCost) with any android 9 - 13 roms based on 4.4,Just be sure that you pick the correct variant like haptics(qti/qpnp) and cam blobs(old/new) according to the rom.

**Comment by enessmr** [comment]
Ok, but OctaviOS (non-official OctaviOS realease) Android 13 tulip has KernelSu. Do you have any ROM's compatible with KernelSU?

**Comment by enessmr** [comment]
btw i dont use root anymore
