### ISSUE TITLE
Broken WiFi on last release.

### ISSUE THREAD

**Issue by Yet-another-NPC-guy** [user-why-red/san_kernel_releases#3]
![Screenshot_2024-08-06-12-09-23-922_com.android.settings.jpg](https://github.com/user-attachments/assets/67642a18-14ea-454a-8e38-016fa7a9a713)

I flashed magisk, maybe magisk fix for WiFi on A10 and lower is missed on this release

**Comment by user-why-red** [comment]
Ahh, Its too late to inform me. Use aurora stable build till new update if you want wifi fixed in android 10 with magisk
